# Generated by Django 5.0.3 on 2024-04-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISA', models.IntegerField()),
                ('ac', models.IntegerField(blank=True, null=True)),
                ('acpall', models.IntegerField(blank=True, null=True)),
                ('ae', models.IntegerField(blank=True, null=True)),
                ('aepall', models.IntegerField(blank=True, null=True)),
                ('ap', models.IntegerField(blank=True, null=True)),
                ('appall', models.IntegerField(blank=True, null=True)),
                ('bc', models.IntegerField(blank=True, null=True)),
                ('bcpall', models.IntegerField(blank=True, null=True)),
                ('be', models.IntegerField(blank=True, null=True)),
                ('bepall', models.IntegerField(blank=True, null=True)),
                ('bp', models.IntegerField(blank=True, null=True)),
                ('bppall', models.IntegerField(blank=True, null=True)),
                ('hc', models.IntegerField(blank=True, null=True)),
                ('hcpall', models.IntegerField(blank=True, null=True)),
                ('he', models.IntegerField(blank=True, null=True)),
                ('hepall', models.IntegerField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('hppall', models.IntegerField(blank=True, null=True)),
                ('fba', models.IntegerField(blank=True, null=True)),
                ('fbacon', models.IntegerField(blank=True, null=True)),
                ('lp', models.IntegerField(blank=True, null=True)),
                ('lppall', models.IntegerField(blank=True, null=True)),
                ('m', models.IntegerField(blank=True, null=True)),
                ('mpall', models.IntegerField(blank=True, null=True)),
                ('par', models.IntegerField(blank=True, null=True)),
                ('parpall', models.IntegerField(blank=True, null=True)),
                ('data_time', models.DateTimeField()),
                ('line', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
