# Generated by Django 5.0.3 on 2024-04-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dock_nyr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='data_time',
            new_name='start_time',
        ),
    ]
