# Generated by Django 5.0.3 on 2024-04-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock_nyr', '0002_rename_data_time_stock_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ac',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
