# Generated by Django 5.0.3 on 2024-05-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock_nyr', '0004_auto_20240419_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
