# Generated by Django 5.1.2 on 2024-11-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock_nyr', '0005_alter_stock_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='ac',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='acpall',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ae',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='aepall',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ap',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='appall',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='bc',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='bcpall',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='be',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='bepall',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='bppall',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fba',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fbacon',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='hc',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='hcpall',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='he',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='hepall',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='hppall',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='lp',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='lppall',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='m',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='mpall',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='par',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='parpall',
        ),
        migrations.AddField(
            model_name='stock',
            name='MIX',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='NVF',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='NVFPP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='NVF_MIX',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='SB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='TSI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='TSI_MIX_P',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='TSI_MIX_U',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='TSI_PAX',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='FBA',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
