# Generated by Django 5.1.2 on 2024-11-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock_nyr', '0006_remove_stock_ac_remove_stock_acpall_remove_stock_ae_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
