# Generated by Django 5.1.5 on 2025-01-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock_nyr', '0007_stock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='delay',
            field=models.TextField(blank=True, null=True),
        ),
    ]
