# Generated by Django 4.0.6 on 2025-03-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock_nyr', '0008_stock_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_stock_data', models.JSONField(verbose_name='Original Stock Data')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Deleted At')),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Deleted By')),
            ],
            options={
                'verbose_name': 'Deleted Stock',
                'verbose_name_plural': 'Deleted Stocks',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-start_time'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AddField(
            model_name='stock',
            name='last_edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_edited_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='FBA',
            field=models.IntegerField(blank=True, help_text='Number of FBA units', null=True, verbose_name='FBA Units'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ISA',
            field=models.IntegerField(verbose_name='ISA Number'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='MIX',
            field=models.IntegerField(blank=True, help_text='Number of mixed units', null=True, verbose_name='MIX Units'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='NVF',
            field=models.IntegerField(blank=True, help_text='Number of NVF units', null=True, verbose_name='NVF Units'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='NVFPP',
            field=models.IntegerField(blank=True, help_text='Number of NVF pallets', null=True, verbose_name='NVF PP'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='NVF_MIX',
            field=models.IntegerField(blank=True, help_text='Number of NVF mixed pallets', null=True, verbose_name='NVF MIX Pallets'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='SB',
            field=models.IntegerField(blank=True, help_text='Number of SB units', null=True, verbose_name='SB'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='TSI',
            field=models.IntegerField(blank=True, help_text='Number of TSI units', null=True, verbose_name='TSI Units'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='TSI_MIX_P',
            field=models.IntegerField(blank=True, help_text='Number of TSI mixed pallets', null=True, verbose_name='TSI MIX Pallets'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='TSI_MIX_U',
            field=models.IntegerField(blank=True, help_text='Number of TSI mixed units', null=True, verbose_name='TSI MIX Units'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='TSI_PAX',
            field=models.IntegerField(blank=True, help_text='Number of TSI pallets', null=True, verbose_name='TSI PAX'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='delay',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Delay Reason'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='line',
            field=models.CharField(max_length=100, verbose_name='Line'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='start_time',
            field=models.DateTimeField(help_text='Format: YYYY-MM-DD HH:MM', verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='user',
            field=models.CharField(blank=True, max_length=50, verbose_name='User'),
        ),
    ]
