# Generated by Django 4.0.6 on 2025-04-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock_nyr', '0009_deletedstock_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['start_time'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_edited_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
