# Generated by Django 4.0.6 on 2025-04-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock_nyr', '0010_alter_stock_options_stock_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sbd_sla_manual_input',
            field=models.CharField(blank=True, help_text='Enter date and time manually (any format).', max_length=100, null=True, verbose_name='Manual SBD/SLA Input'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='This field stores the processed date/time.', null=True, verbose_name='SBD/SLA (Processed)'),
        ),
    ]
