# Generated by Django 5.1.7 on 2025-07-17 04:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock_nyr', '0011_stock_sbd_sla_manual_input_alter_stock_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotomHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_id', models.CharField(db_index=True, max_length=50, verbose_name='Trailer ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='Event Type')),
                ('event_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event Timestamp')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='User')),
                ('isa', models.IntegerField(blank=True, null=True, verbose_name='ISA Number')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
            ],
            options={
                'verbose_name': 'ROTOM History Event',
                'verbose_name_plural': 'ROTOM History Events',
                'ordering': ['-event_timestamp'],
            },
        ),
    ]
