# Generated by Django 5.1.7 on 2025-07-18 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock_nyr', '0012_rotomhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotomState',
            fields=[
                ('trailer_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Trailer ID')),
                ('last_known_isa', models.IntegerField(blank=True, null=True, verbose_name='Last Known ISA')),
                ('status', models.CharField(default='released', max_length=20, verbose_name='Status')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RotomSummary',
            fields=[
                ('id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('reloaded_trailers', models.JSONField(default=list, verbose_name='Reloaded Trailers List')),
                ('released_trailers', models.JSONField(default=list, verbose_name='Released Trailers List')),
                ('last_reset', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'ROTOM Summary Counters',
            },
        ),
    ]
