# Generated by Django 5.1.7 on 2025-07-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock_nyr', '0013_rotomstate_rotomsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotomsummary',
            name='is_initialized',
            field=models.BooleanField(default=False, verbose_name='Is Initialized'),
        ),
    ]
